version: "3"

services:
  db:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - POSTGRES_USER=onedev
      - POSTGRES_PASSWORD=onedev
      - POSTGRES_DB=onedev
    ports:
      - 5339:5432  
    volumes:
      - ./postgres:/var/lib/postgresql/data


  onedev-app:
    container_name: onedev-app
    image: 1dev/server:8.0.15
    ports:
      - 6610:6610
      - 6611:6611
    environment:
      - hibernate_cdialect=io.onedev.server.persistence.PostgreSQLDialect
      - hibernate_cconnection_driver_class=org.postgresql.Driver
      - hibernate_cconnection_url=jdbc:postgresql://localhost:5432/onedev
      - hibernate_cconnection_username=postgres
      - hibernate_cconnection_password=postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker_data/onedev:/opt/onedev
    restart: unless-stopped
    depends_on:
      - db

volumes:
  onedev: